"""initial

Revision ID: 3bc9cba82d10
Revises: 
Create Date: 2024-01-12 05:20:34.122964

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3bc9cba82d10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('last_request', sa.DateTime(), nullable=True),
    sa.Column('requests_per_day', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('requests_per_day >= 0', name='requests_per_day_not_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('telegram_id', name='telegram_id_uniq')
    )
    op.create_table('wb_account',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_now_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name='uniq_account_name')
    )
    op.create_table('account_favorites_requests',
    sa.Column('wb_account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('nm_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wb_account_id'], ['wb_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wb_account_id', 'nm_id', 'period', name='all_columns_uniq')
    )
    op.create_table('wb_tokens',
    sa.Column('wb_account_id', sa.Integer(), nullable=False),
    sa.Column('wb_token_content', sa.LargeBinary(), nullable=True),
    sa.Column('wb_token_analytic', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wb_account_id'], ['wb_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_tokens')
    op.drop_table('account_favorites_requests')
    op.drop_table('wb_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
